# Generated by Django 4.2.15 on 2024-08-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('license_id', models.CharField(max_length=20)),
                ('affidavit_or_police_report', models.FileField(upload_to='affidavits_reports/')),
            ],
        ),
    ]
