# Generated by Django 5.0.6 on 2024-09-02 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseApplication', '0002_alter_newlicenseapplication_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlicenseapplication',
            name='email',
            field=models.EmailField(default=1, max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='local_government',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newlicenseapplication',
            name='street_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reissuelicenseapplication',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='renewallicenseapplication',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
    ]
