# Generated by Django 5.0.6 on 2024-09-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenseApplication", "0006_alter_newlicenseapplication_facial_mark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newlicenseapplication",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default=1,
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newlicenseapplication",
            name="middle_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newlicenseapplication",
            name="next_of_kin_phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
