# Generated by Django 5.0.6 on 2024-09-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseApplication', '0007_alter_newlicenseapplication_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='validity_year',
            field=models.IntegerField(choices=[(3, '3 Years'), (5, '5 Years')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='vehicle_type',
            field=models.CharField(choices=[('A', 'Motorcycle'), ('B', 'Light Vehicle'), ('C', 'Light Commercial Vehicle'), ('D', 'Medium Vehicle'), ('E', 'Heavy Vehicle'), ('F', 'Agricultural Vehicles'), ('G', 'Articulated Vehicles'), ('H', 'Construction Vehicles'), ('I', 'Special Vehicles for Physically Handicapped Persons')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
