# Generated by Django 4.2.15 on 2024-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_renewal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('license_id', models.CharField(max_length=20, unique=True)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='LicenseRenewal',
        ),
    ]
